export type ErrorCode =
  | "VALIDATION_ERROR"
  | "LOCKER_IDENTIFIER_EXISTS"
  | "LOCKER_NOT_FOUND"
  | "NO_AVAILABLE_LOCKER"
  | "PACKAGE_NOT_FOUND"
  | "PICKUP_CODE_GENERATION_FAILED"
  | "INTERNAL_SERVER_ERROR";
